### ISSUE TITLE
[Feature] CI/CD Pipeline for Automated Test Execution

### ISSUE THREAD

**Issue by GBHU753** [UoaWDCC/aspa-portal-v3#131]
## User story

As a **developer** and **DevOps engineer**, I want **an automated CI/CD pipeline, powered by GitHub Actions, that runs all relevant project tests (unit, integration, frontend, etc.) on every code change**, so that **I can get immediate feedback on code quality, catch regressions early, ensure all tests pass before merging, and ultimately build confidence in our releases.**

## Acceptance criteria

*   [ ] The **GitHub Actions workflow** is automatically triggered on specified events (e.g., every push to a branch, every Pull Request creation/update).
*   [ ] The workflow executes all configured test suites (e.g., backend unit tests, frontend component tests, API integration tests).
*   [ ] The test execution status (pass/fail) is reported back to GitHub Pull Request status checks.
*   [ ] The workflow job fails if any test fails, preventing the merge of broken code.
*   [ ] Test results (e.g., detailed logs, test reports, coverage reports) are accessible within the GitHub Actions run logs.
*   [ ] The test environment in GitHub Actions accurately reflects the development environment (e.g., correct Node.js version, database setup if needed).

## User story

As a **developer** and **DevOps engineer**, I want **an automated CI/CD pipeline, powered by GitHub Actions, that runs all relevant project tests (unit, integration, frontend, etc.) on every code change**, so that **I can get immediate feedback on code quality, catch regressions early, ensure all tests pass before merging, and ultimately build confidence in our releases.**

## Definition of done

*   [ ] Acceptance criteria met
*   [ ] PR reviewed (for the `.github/workflows/*.yml` configuration file)
*   [ ] Merged into the main/feature branch

## Notes

*   **GitHub Actions Configuration:**
    *   Workflows are defined in `.github/workflows/` directory as `.yml` files.
    *   Example basic structure:
        ```yaml
        name: Run Tests

        on:
          push:
            branches:
              - main
              - develop
          pull_request:
            branches:
              - main
              - develop

        jobs:
          test:
            runs-on: ubuntu-latest # Or windows-latest, macos-latest
            steps:
              - uses: actions/checkout@v4
              - uses: actions/setup-node@v4
                with:
                  node-version: '20' # Specify your Node.js version

              - name: Install dependencies
                run: yarn install --frozen-lockfile # or npm ci

              - name: Run tests
                run: yarn test # or npm test

              # Optional: Run linting
              - name: Run lint
                run: yarn lint

              # Optional: Build project to check buildability
              - name: Build project
                run: yarn build
        ```
*   **Trigger Events:**
    *   Use `on: push` to trigger on pushes to specified branches.
    *   Use `on: pull_request` to trigger on PR open, updates, etc. This is crucial for PR status checks.
*   **Environment Setup:**
    *   Use `actions/setup-node@v4` to easily set up the required Node.js version.
    *   **Caching dependencies:** Use `actions/cache@v4` to significantly speed up `yarn install` or `npm install`.
        ```yaml
        - name: Cache dependencies
          uses: actions/cache@v4
          with:
            path: ~/.yarn
            key: ${{ runner.os }}-node-${{ hashFiles('**/yarn.lock') }}
            restore-keys: |
              ${{ runner.os }}-node-
        ```
    *   **Services (for databases, etc.):** If your tests require a database (e.g., PostgreSQL, MongoDB) or other services, you can configure them using the `services` keyword in your job.
        ```yaml
        jobs:
          test:
            runs-on: ubuntu-latest
            services:
              postgres:
                image: postgres:13
                env:
                  POSTGRES_DB: testdb
                  POSTGRES_USER: user
                  POSTGRES_PASSWORD: password
                ports:
                  - 5432:5432
                options: >-
                  --health-cmd pg_isready
                  --health-interval 10s
                  --health-timeout 5s
                  --health-retries 5
            steps:
              # ... your steps, tests can connect to localhost:5432
        ```
*   **Reporting & Test Results:**
    *   GitHub Actions automatically parses test failures from console output.
    *   For richer test reports (e.g., showing individual test cases, coverage trends):
        *   **Test Reporter Action:** Use an action like `dorny/test-reporter@v1` to display JUnit XML reports directly in the workflow summary.
        *   **Code Coverage:** Generate coverage reports (`jest --coverage`) and use an action like `codecov/codecov-action@v3` to upload them to Codecov for tracking.
*   **Security:**
    *   Store sensitive information (API keys, database credentials) as **GitHub Secrets** in your repository settings.
    *   Access them in your workflow using `secrets.YOUR_SECRET_NAME`. For example:
        ```yaml
        - name: Run tests with API key
          run: YOUR_API_KEY=${{ secrets.MY_API_KEY }} yarn test
        ```
